CREATE TABLE IF NOT EXISTS "USERS" (
  "USER_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EMAIL" varchar(100),
  "LOGIN" varchar(100),
  "NAME" varchar(100),
  "BIRTHDAY" timestamp
);

CREATE TABLE IF NOT EXISTS "FRIENDS" (
  "USER_ID" integer,
  "FRIEND_ID" integer,
  "STATUS" integer
);

CREATE TABLE IF NOT EXISTS"FILMLIKES" (
  "FILM_ID" integer,
  "USER_ID" integer
);

CREATE TABLE IF NOT EXISTS "FILM" (
  "FILM_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NAME" varchar(100),
  "DESCRIPTION" varchar(256),
  "RELEASE_DATE" timestamp,
  "DURATION" integer,
  "GENRE" varchar(20),
  "RATING" varchar(10)
);

COMMENT ON COLUMN "Friends"."status" IS '1 - accepted invitation, 0  - unaccepted';

ALTER TABLE "USERS" ADD FOREIGN KEY ("USER_ID") REFERENCES "Filmlikes" ("USER_ID");

ALTER TABLE "Film" ADD FOREIGN KEY ("FILM_ID") REFERENCES "Filmlikes" ("FILM_ID");

ALTER TABLE "USERS" ADD FOREIGN KEY ("USER_ID") REFERENCES "Friends" ("USER_ID");

ALTER TABLE "USERS" ADD FOREIGN KEY ("USER_ID") REFERENCES "Friends" ("friend_id");
