CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
	USER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	EMAIL CHARACTER VARYING(100),
	LOGIN CHARACTER VARYING(100),
	NAME CHARACTER VARYING(100),
	BIRTHDAY TIMESTAMP,
	CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
	FILM_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME CHARACTER VARYING(100),
	DESCRIPTION CHARACTER VARYING(256),
	RELEASE_DATE TIMESTAMP,
	DURATION INTEGER,
	CONSTRAINT FILM_PK PRIMARY KEY (FILM_ID)
);


CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDS (
	USER_ID INTEGER NOT NULL,
	FRIEND_ID INTEGER NOT NULL,
	STATUS INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT FRIENDS_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FRIENDS_FK_1 FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS "FILMLIKES" (
  "FILM_ID" integer,
  "USER_ID" integer,
    CONSTRAINT fk_FILM_ID
      FOREIGN KEY(FILM_ID)
      REFERENCES FILMS(FILM_ID),
	CONSTRAINT fk_USER_ID
      FOREIGN KEY(USER_ID)
      REFERENCES USERS(USER_ID)
);
CREATE TABLE IF NOT EXISTS PUBLIC.MPA (
	MPA_ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING,
	CONSTRAINT MPA_PK PRIMARY KEY (MPA_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRES (
	GENRE_ID INTEGER NOT NULL,
	NAME CHARACTER VARYING,
	CONSTRAINT GENRES_PK PRIMARY KEY (GENRE_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRES_FILM (
	FILM_ID INTEGER NOT NULL,
	GENRE_ID INTEGER NOT NULL,
	CONSTRAINT GENRES_FILM_FK FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRES(GENRE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT GENRES_FILM_FK_1 FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);


CREATE TABLE IF NOT EXISTS PUBLIC.MPA_FILM (
	MPA_ID INTEGER NOT NULL REFERENCES PUBLIC.MPA(MPA_ID),
	FILM_ID INTEGER NOT NULL REFERENCES PUBLIC.FILMS(FILM_ID)
);
--DIRECTORS UPDATE
CREATE TABLE IF NOT EXISTS PUBLIC.DIRECTORS (
  "DIRECTOR_ID" INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  "NAME" CHARACTER VARYING NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.DIRECTORS_FILM (
  "FILM_ID" INTEGER NOT NULL,
  "DIRECTOR_ID" INTEGER NOT NULL,
  	CONSTRAINT DIRECTORS_FILM_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT DIRECTORS_FILM_FK_1 FOREIGN KEY (DIRECTOR_ID) REFERENCES PUBLIC.DIRECTORS(DIRECTOR_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
--



